#
# Macro file for "Hadr03.cc"
#
/control/verbose 2
/run/verbose 2
#
/testhadr/det/setMat G4_Bi
#
/run/initialize
#
/gun/particle proton
/gun/energy 1 TeV
#
/process/list
/process/inactivate hadElastic
#
/analysis/setFileName inelastic
/analysis/h1/set 2  100  0. 8000 keV	#gamma
/analysis/h1/set 8  100  0.  400 keV	#nuclei
/analysis/h1/set 11 100 -10  +0  MeV	#Q
#
/run/printProgress 1000
/run/beamOn 10000
